### ISSUE TITLE
Не определяет пол по имени "Анна"

### ISSUE THREAD

**Issue by ice1x** [Rai220/MlSexDetector#1]
**Actual:**
Не определяет пол по имени "Анна".
Даже после переобучения по bigdata.

`Input name: анна`
`Sex:  unknown`
`[[0.7022238  0.09820845 0.19956774]]`
`Input name: Анна`
`Sex:  unknown`
`[[0.7022238  0.09820845 0.19956774]]`

**Expected:**
Ожидается, что Анна - это женское имя.

**Comment by Rai220** [comment]
Спасибо за замечание, проблема была в том, что модель не реагировала на отдельные имена, только ФИО или ИМЯ + ФАМИЛИЯ. Поправил.
